export const FETCH_LIST_HOTELS = 'FETCH_LIST_HOTELS';
export const FETCH_LIST_HOTELS_SUCCESS = 'FETCH_LIST_HOTELS_SUCCESS';
export const FETCH_LIST_HOTELS_FAIL = 'FETCH_LIST_HOTELS_FAIL';

export const ADD_HOTEL = 'ADD_HOTEL';
export const ADD_HOTEL_SUCCESS= 'ADD_HOTEL_SUCCESS';
export const ADD_HOTEL_FAIL = 'ADD_HOTEL_FAIL';

export const EDIT_HOTEL = 'EDIT_HOTEL';
export const EDIT_HOTEL_SUCCESS= 'EDIT_HOTEL_SUCCESS';
export const EDIT_HOTEL_FAIL = 'EDIT_HOTEL_FAIL';

export const DELETE_HOTEL = 'DELETE_HOTEL';
export const DELETE_HOTEL_SUCCESS= 'DELETE_HOTEL_SUCCESS';
export const DELETE_HOTEL_FAIL = 'DELETE_HOTEL_FAIL';
