export const FETCH_LIST_ROOMS = 'FETCH_LIST_ROOMS';
export const FETCH_LIST_ROOMS_SUCCESS = 'FETCH_LIST_ROOMS_SUCCESS';
export const FETCH_LIST_ROOMS_FAIL = 'FETCH_LIST_ROOMS_FAIL';

export const ADD_ROOM = 'ADD_ROOM';
export const ADD_ROOM_SUCCESS= 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';

export const EDIT_ROOM = 'EDIT_ROOM';
export const EDIT_ROOM_SUCCESS= 'EDIT_ROOM_SUCCESS';
export const EDIT_ROOM_FAIL = 'EDIT_ROOM_FAIL';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS= 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';
